<a href="https://colab.research.google.com/github/lakshmigojanece/assignment_2/blob/main/online_food_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#online food delivery probject

In [ ]:
#DATA COLLECTION:

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/sample_data/Untitled Folder/ONINE_FOOD_DELIVERY_ANALYSIS (2).csv")

In [ ]:
df.shape

(100000, 25)

In [ ]:
#DATA UNDERSTANDING:processing

In [ ]:
#first,i was checked,how many columns

In [ ]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Age', 'Customer_Gender', 'City',
       'Area', 'Restaurant_ID', 'Restaurant_Name', 'Cuisine_Type',
       'Order_Date', 'Order_Time', 'Delivery_Time_Min', 'Distance_km',
       'Order_Value', 'Discount_Applied', 'Final_Amount', 'Payment_Mode',
       'Order_Status', 'Cancellation_Reason', 'Delivery_Partner_ID',
       'Delivery_Rating', 'Restaurant_Rating', 'Order_Day', 'Peak_Hour',
       'Profit_Margin'],
      dtype='object')

In [ ]:
df

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,NaN,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,8/12/2024,...,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12/8/2024,...,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10/8/2024,...,NaN,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2/4/2024,...,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD099996,CUST3722,NaN,NaN,Mumbai,NaN,RES295,Restaurant_500,Arabian,6/10/2024,...,132.0,Card,Delivered,NaN,DP835,2.0,4.0,Weekday,True,0.17
99996,ORD099997,CUST6158,NaN,Male,Mumbai,East,RES157,Restaurant_458,Arabian,4/22/2024,...,1078.0,NaN,Delivered,NaN,DP476,4.0,3.5,Weekday,False,-0.15
99997,ORD099998,CUST2155,NaN,NaN,Delhi,East,RES287,Restaurant_273,NaN,2/23/2024,...,NaN,COD,Cancelled,NaN,DP577,2.0,4.0,Weekday,True,0.47
99998,ORD099999,CUST3015,NaN,Female,Delhi,North,RES491,Restaurant_241,NaN,12/10/2024,...,NaN,NaN,Delivered,NaN,DP896,NaN,4.3,Weekday,NaN,0.44
99999,ORD100000,CUST7959,NaN,Other,Hyderabad,East,RES680,Restaurant_237,Chinese,NaN,...,NaN,Wallet,Cancelled,NaN,DP908,5.0,4.2,Weekday,False,0.20

In [ ]:
df.isnull().sum()

Order_ID                   0
Customer_ID                0
Customer_Age           50093
Customer_Gender        24856
City                   16726
Area                   16685
Restaurant_ID              0
Restaurant_Name            0
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Delivery_Time_Min      33359
Distance_km            33470
Order_Value            33327
Discount_Applied       16715
Final_Amount           55697
Payment_Mode           19911
Order_Status               0
Cancellation_Reason    90969
Delivery_Partner_ID        0
Delivery_Rating        16523
Restaurant_Rating          0
Order_Day                  0
Peak_Hour              32962
Profit_Margin              0
dtype: int64

In [ ]:
df.groupby('Peak_Hour')['Delivery_Time_Min'].mean()

Peak_Hour
False    127.981911
True     127.049402
Name: Delivery_Time_Min, dtype: float64

In [ ]:
#order_value is 0.00 overall 100000 rows but this is say peak_value is true and false i will analysis this data is order_hour is 0.00 and also peak_hour all rows is false only and  same time  peak_hour  is 6 to 11 morining, 12 to 1 afternoon, 4 to 7 evening, 7 to 9 night

In [ ]:
df.Customer_Age.value_counts()

Customer_Age
27.0    1260
33.0    1250
49.0    1243
34.0    1208
23.0    1201
46.0    1196
53.0    1196
19.0    1193
56.0    1190
55.0    1185
40.0    1179
44.0    1177
29.0    1174
39.0    1173
48.0    1172
42.0    1166
30.0    1166
36.0    1165
51.0    1163
38.0    1162
57.0    1162
45.0    1161
18.0    1157
37.0    1156
21.0    1154
50.0    1152
25.0    1151
32.0    1148
43.0    1146
26.0    1146
35.0    1144
54.0    1137
41.0    1137
22.0    1136
47.0    1131
20.0    1131
52.0    1129
24.0    1123
59.0    1118
60.0    1116
58.0    1096
28.0    1084
31.0    1073
Name: count, dtype: int64

In [ ]:
df.describe() # numerical value only

,Customer_Age,Delivery_Time_Min,Distance_km,Order_Value,Discount_Applied,Final_Amount,Delivery_Rating,Restaurant_Rating,Profit_Margin
count,49907.000000,66641.000000,66530.000000,66673.000000,83285.000000,44303.000000,83477.000000,100000.000000,100000.000000
mean,38.976516,127.475923,16.449242,2081.830126,93.936243,1961.101190,2.991531,4.249680,0.150362
std,12.372157,90.805839,12.256742,1553.628891,108.209904,1557.354417,1.414108,0.722554,0.201888
min,18.000000,20.000000,1.000000,150.000000,0.000000,-150.000000,1.000000,3.000000,-0.200000
25%,28.000000,45.000000,5.470000,673.000000,20.000000,559.000000,2.000000,3.600000,-0.020000
50%,39.000000,120.000000,9.970000,1197.000000,50.000000,1156.000000,3.000000,4.200000,0.150000
75%,50.000000,210.000000,27.430000,3494.000000,100.000000,3375.000000,4.000000,4.900000,0.320000
max,60.000000,300.000000,40.000000,5000.000000,300.000000,4980.000000,5.000000,5.500000,0.500000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             100000 non-null  object
 1   Customer_ID          100000 non-null  object
 2   Customer_Age         49907 non-null   float64
 3   Customer_Gender      75144 non-null   object
 4   City                 83274 non-null   object
 5   Area                 83315 non-null   object
 6   Restaurant_ID        100000 non-null  object
 7   Restaurant_Name      100000 non-null  object
 8   Cuisine_Type         83115 non-null   object
 9   Order_Date           98986 non-null   object
 10  Order_Time           98002 non-null   object
 11  Delivery_Time_Min    66641 non-null   float64
 12  Distance_km          66530 non-null   float64
 13  Order_Value          66673 non-null   float64
 14  Discount_Applied     83285 non-null   float64
 15  Final_Amount         44303 non-null   float64
 16  Payment_Mode         80089 non-null   object
 17  Order_Status         100000 non-null  object
 18  Cancellation_Reason  9031 non-null    object
 19  Delivery_Partner_ID  100000 non-null  object
 20  Delivery_Rating      83477 non-null   float64
 21  Restaurant_Rating    100000 non-null  float64
 22  Order_Day            100000 non-null  object
 23  Peak_Hour            67038 non-null   object
 24  Profit_Margin        100000 non-null  float64
dtypes: float64(9), object(16)
memory usage: 19.1+ MB

In [ ]:
df['Delivery_Rating'].isna().sum()

np.int64(16523)

In [ ]:
df['Delivery_Rating'].fillna(df['Delivery_Rating'].median(), inplace=True)##high outlier

/tmp/ipython-input-2511190309.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Delivery_Rating'].fillna(df['Delivery_Rating'].median(), inplace=True)##high outlier

In [ ]:
df.Delivery_Rating.median(),df.Delivery_Rating.mean(),df.Delivery_Rating.mode()

(3.0,
 np.float64(2.99293),
 0    3.0
 Name: Delivery_Rating, dtype: float64)

In [ ]:
df.Delivery_Rating.value_counts(),df.Delivery_Rating.value_counts().sum()

(Delivery_Rating
 3.0    32931
 2.0    16896
 4.0    16885
 1.0    16818
 5.0    16470
 Name: count, dtype: int64,
 np.int64(100000))

In [ ]:
df['Final_Amount'].fillna(df['Final_Amount'].median(),inplace=True)# this is int value but

/tmp/ipython-input-562559247.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Final_Amount'].fillna(df['Final_Amount'].median(),inplace=True)# this is int value but

In [ ]:
df.Final_Amount.median(),df.Final_Amount.mean()## high outlier because i was used median

(1156.0, np.float64(1512.68398))

In [ ]:
df.Final_Amount.value_counts(),df.Final_Amount.value_counts().sum()

(Final_Amount
  1156.0    55707
  338.0        37
  512.0        35
  603.0        33
  754.0        33
            ...
 -88.0          1
  4961.0        1
  1814.0        1
  1890.0        1
  1756.0        1
 Name: count, Length: 4574, dtype: int64,
 np.int64(100000))

In [ ]:
df.Discount_Applied.median(),df.Discount_Applied.mean()## high outlier

(50.0, np.float64(93.93624302095215))

In [ ]:
df['Discount_Applied'].fillna(df['Discount_Applied'].median(),inplace=True)

/tmp/ipython-input-1910732480.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Discount_Applied'].fillna(df['Discount_Applied'].median(),inplace=True)

In [ ]:
df.Discount_Applied.value_counts(),df.Discount_Applied.value_counts().sum()

(Discount_Applied
 50.0     33405
 100.0    16776
 0.0      16650
 300.0    16600
 20.0     16569
 Name: count, dtype: int64,
 np.int64(100000))

In [ ]:
df.Order_Value.median(),df.Order_Value.mean()#high outlier so, i was used median

(1197.0, np.float64(2081.830126138017))

In [ ]:
df['Order_Value'].fillna(df['Order_Value'].median(),inplace=True)

/tmp/ipython-input-3085633638.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Order_Value'].fillna(df['Order_Value'].median(),inplace=True)

In [ ]:
df.Order_Value.value_counts(),df.Order_Value.value_counts().sum()

(Order_Value
 1197.0    33363
 1108.0       52
 198.0        49
 1183.0       49
 1091.0       48
           ...
 2156.0        3
 3078.0        3
 3986.0        3
 4533.0        3
 3720.0        3
 Name: count, Length: 4052, dtype: int64,
 np.int64(100000))

In [ ]:
df.Distance_km.mean(),df.Distance_km.median()## high outlier

(np.float64(16.449242447016385), 9.97)

In [ ]:
df['Distance_km'].fillna(df['Distance_km'].median(),inplace=True)

/tmp/ipython-input-973713674.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Distance_km'].fillna(df['Distance_km'].median(),inplace=True)

In [ ]:
df.Distance_km.value_counts(),df.Distance_km.value_counts().sum()

(Distance_km
 9.97     33516
 1.97        59
 2.01        54
 7.85        53
 1.24        53
          ...
 21.40        4
 38.70        4
 20.29        3
 35.90        3
 15.16        2
 Name: count, Length: 3402, dtype: int64,
 np.int64(100000))

In [ ]:
df['Delivery_Time_Min'].fillna(df['Delivery_Time_Min'].median(), inplace=True)

/tmp/ipython-input-1646966748.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Delivery_Time_Min'].fillna(df['Delivery_Time_Min'].median(), inplace=True)

In [ ]:
df.Delivery_Time_Min.median(),round(df.Delivery_Time_Min.mean())## this is outlier

(120.0, 125)

In [ ]:
df.Delivery_Time_Min.value_counts(),df.Delivery_Time_Min.value_counts().sum()

(Delivery_Time_Min
 120.0    33545
 36.0       710
 42.0       709
 64.0       702
 26.0       687
          ...
 298.0      158
 292.0      156
 295.0      152
 160.0      148
 246.0      148
 Name: count, Length: 232, dtype: int64,
 np.int64(100000))

In [ ]:
df.dtypes

Order_ID                object
Customer_ID             object
Customer_Age           float64
Customer_Gender         object
City                    object
Area                    object
Restaurant_ID           object
Restaurant_Name         object
Cuisine_Type            object
Order_Date              object
Order_Time              object
Delivery_Time_Min      float64
Distance_km            float64
Order_Value            float64
Discount_Applied       float64
Final_Amount           float64
Payment_Mode            object
Order_Status            object
Cancellation_Reason     object
Delivery_Partner_ID     object
Delivery_Rating        float64
Restaurant_Rating      float64
Order_Day               object
Peak_Hour               object
Profit_Margin          float64
dtype: object

In [ ]:
df.shape

(100000, 25)

In [ ]:
df.isnull().sum()

Order_ID                   0
Customer_ID                0
Customer_Age           50093
Customer_Gender        24856
City                   16726
Area                   16685
Restaurant_ID              0
Restaurant_Name            0
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Delivery_Time_Min          0
Distance_km                0
Order_Value                0
Discount_Applied           0
Final_Amount               0
Payment_Mode           19911
Order_Status               0
Cancellation_Reason    90969
Delivery_Partner_ID        0
Delivery_Rating            0
Restaurant_Rating          0
Order_Day                  0
Peak_Hour              32962
Profit_Margin              0
dtype: int64

In [ ]:
df.head()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,1156.0,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,8/12/2024,...,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12/8/2024,...,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10/8/2024,...,1156.0,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2/4/2024,...,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12

In [ ]:
df.nunique()

Order_ID               100000
Customer_ID              8999
Customer_Age               43
Customer_Gender             3
City                        5
Area                        5
Restaurant_ID             900
Restaurant_Name           500
Cuisine_Type                5
Order_Date                365
Order_Time                  1
Delivery_Time_Min         232
Distance_km              3402
Order_Value              4052
Discount_Applied            5
Final_Amount             4574
Payment_Mode                4
Order_Status                2
Cancellation_Reason         3
Delivery_Partner_ID       900
Delivery_Rating             5
Restaurant_Rating          26
Order_Day                   2
Peak_Hour                   2
Profit_Margin              71
dtype: int64

In [ ]:
#df['Customer_Gender'].fillna(df['Customer_Gender'].mode()[0], inplace=True)

In [ ]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.Customer_Age.mean(),round(df.Customer_Age.mean())

(np.float64(38.97651632035586), 39)

In [ ]:
df['Customer_Age'].fillna(round(df['Customer_Age'].mean()), inplace=True)## this is not outlier so i was used mean

/tmp/ipython-input-1241881943.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_Age'].fillna(round(df['Customer_Age'].mean()), inplace=True)## this is not outlier so i was used mean

In [ ]:
df.isnull().sum()

Order_ID                   0
Customer_ID                0
Customer_Age               0
Customer_Gender        24856
City                   16726
Area                   16685
Restaurant_ID              0
Restaurant_Name            0
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Delivery_Time_Min          0
Distance_km                0
Order_Value                0
Discount_Applied           0
Final_Amount               0
Payment_Mode           19911
Order_Status               0
Cancellation_Reason    90969
Delivery_Partner_ID        0
Delivery_Rating            0
Restaurant_Rating          0
Order_Day                  0
Peak_Hour              32962
Profit_Margin              0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             100000 non-null  object
 1   Customer_ID          100000 non-null  object
 2   Customer_Age         100000 non-null  float64
 3   Customer_Gender      75144 non-null   object
 4   City                 83274 non-null   object
 5   Area                 83315 non-null   object
 6   Restaurant_ID        100000 non-null  object
 7   Restaurant_Name      100000 non-null  object
 8   Cuisine_Type         83115 non-null   object
 9   Order_Date           98986 non-null   object
 10  Order_Time           98002 non-null   object
 11  Delivery_Time_Min    100000 non-null  float64
 12  Distance_km          100000 non-null  float64
 13  Order_Value          100000 non-null  float64
 14  Discount_Applied     100000 non-null  float64
 15  Final_Amount         100000 non-null  float64
 16  Payment_Mode         80089 non-null   object
 17  Order_Status         100000 non-null  object
 18  Cancellation_Reason  9031 non-null    object
 19  Delivery_Partner_ID  100000 non-null  object
 20  Delivery_Rating      100000 non-null  float64
 21  Restaurant_Rating    100000 non-null  float64
 22  Order_Day            100000 non-null  object
 23  Peak_Hour            67038 non-null   object
 24  Profit_Margin        100000 non-null  float64
dtypes: float64(9), object(16)
memory usage: 19.1+ MB

In [ ]:
df['Peak_Hour'].fillna(df['Peak_Hour'].mode()[0],inplace=True)

/tmp/ipython-input-4245931762.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Peak_Hour'].fillna(df['Peak_Hour'].mode()[0],inplace=True)
/tmp/ipython-input-4245931762.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Peak_Hour'].fillna(df['Peak_Hour'].mode()[0],inplace=True)

In [ ]:
df.Peak_Hour.value_counts(),df.Peak_Hour.value_counts().sum()

(Peak_Hour
 False    66547
 True     33453
 Name: count, dtype: int64,
 np.int64(100000))

In [ ]:
df['Peak_Hour']

0         True
1         True
2         True
3        False
4        False
         ...
99995     True
99996    False
99997     True
99998    False
99999    False
Name: Peak_Hour, Length: 100000, dtype: bool

In [ ]:
df['Cancellation_Reason'].fillna('Not Cancelled', inplace=True)

/tmp/ipython-input-102152185.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cancellation_Reason'].fillna('Not Cancelled', inplace=True)

In [ ]:
df.Cancellation_Reason.value_counts(),df.Cancellation_Reason.value_counts().sum()

(Cancellation_Reason
 Not Cancelled         90969
 Late Delivery          3059
 Customer Cancelled     2993
 Restaurant Issue       2979
 Name: count, dtype: int64,
 np.int64(100000))

In [ ]:
df['Cancellation_Reason']

0        Not Cancelled
1        Not Cancelled
2        Not Cancelled
3        Late Delivery
4        Not Cancelled
             ...
99995    Not Cancelled
99996    Not Cancelled
99997    Not Cancelled
99998    Not Cancelled
99999    Not Cancelled
Name: Cancellation_Reason, Length: 100000, dtype: object

In [ ]:
df['Payment_Mode'].fillna(df['Payment_Mode'].mode()[0],inplace=True)## this string value so i was used mode

/tmp/ipython-input-79719317.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Payment_Mode'].fillna(df['Payment_Mode'].mode()[0],inplace=True)## this string value so i was used mode

In [ ]:
df.Payment_Mode.value_counts(),df.Payment_Mode.value_counts().sum()

(Payment_Mode
 Card      40005
 Wallet    20086
 COD       19977
 UPI       19932
 Name: count, dtype: int64,
 np.int64(100000))

In [ ]:
df['Payment_Mode']

0           UPI
1           COD
2        Wallet
3           UPI
4          Card
          ...
99995      Card
99996      Card
99997       COD
99998      Card
99999    Wallet
Name: Payment_Mode, Length: 100000, dtype: object

In [ ]:
df['Order_Time'].fillna(df['Order_Time'].mode()[0], inplace=True)

/tmp/ipython-input-2869848219.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Order_Time'].fillna(df['Order_Time'].mode()[0], inplace=True)

In [ ]:
df['Order_Time']

0        0:00
1        0:00
2        0:00
3        0:00
4        0:00
         ...
99995    0:00
99996    0:00
99997    0:00
99998    0:00
99999    0:00
Name: Order_Time, Length: 100000, dtype: object

In [ ]:
df.Order_Time.value_counts(),df.Order_Time.value_counts().sum()

(Order_Time
 0:00    100000
 Name: count, dtype: int64,
 np.int64(100000))

In [ ]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [ ]:
#df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [ ]:
df['Order_Date'].fillna(df['Order_Date'].mode()[0], inplace=True)

/tmp/ipython-input-2000339243.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Order_Date'].fillna(df['Order_Date'].mode()[0], inplace=True)

In [ ]:
df.Order_Date.value_counts(),df.Order_Date.value_counts().sum()

(Order_Date
 2024-07-15    1336
 2024-06-22     318
 2024-07-14     311
 2024-09-08     308
 2024-09-02     308
               ...
 2024-10-27     235
 2024-10-05     235
 2024-04-11     228
 2024-03-07     223
 2024-08-21     221
 Name: count, Length: 365, dtype: int64,
 np.int64(100000))

In [ ]:
df.Cuisine_Type.value_counts(),df.Cuisine_Type.value_counts().sum()

(Cuisine_Type
 Indian     33570
 Arabian    16658
 Chinese    16651
 Mexican    16602
 Italian    16519
 Name: count, dtype: int64,
 np.int64(100000))

In [ ]:
df['Cuisine_Type'].fillna(df['Cuisine_Type'].mode()[0],inplace=True)

/tmp/ipython-input-2337185126.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cuisine_Type'].fillna(df['Cuisine_Type'].mode()[0],inplace=True)

In [ ]:
df.Area.value_counts(),df.Area.value_counts().sum()

(Area
 South      33410
 North      16675
 West       16653
 East       16643
 Central    16619
 Name: count, dtype: int64,
 np.int64(100000))

In [ ]:
df['Area'].fillna(df['Area'].mode()[0],inplace=True)

/tmp/ipython-input-1709026974.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Area'].fillna(df['Area'].mode()[0],inplace=True)

In [ ]:
df.City.value_counts(),df.City.value_counts().sum()

(City
 Hyderabad    33610
 Bangalore    16732
 Delhi        16695
 Mumbai       16493
 Chennai      16470
 Name: count, dtype: int64,
 np.int64(100000))

In [ ]:
df['City'].fillna(df['City'].mode()[0],inplace=True)

/tmp/ipython-input-689064380.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].fillna(df['City'].mode()[0],inplace=True)

In [ ]:
df['Customer_Gender'].value_counts().sum(),df['Customer_Gender'].value_counts()

(np.int64(100000),
 Customer_Gender
 Other     49991
 Female    25031
 Male      24978
 Name: count, dtype: int64)

In [ ]:
df['Customer_Gender'].fillna(df['Customer_Gender'].mode()[0], inplace=True)

In [ ]:
df.isnull().sum()

Order_ID               0
Customer_ID            0
Customer_Age           0
Customer_Gender        0
City                   0
Area                   0
Restaurant_ID          0
Restaurant_Name        0
Cuisine_Type           0
Order_Date             0
Order_Time             0
Delivery_Time_Min      0
Distance_km            0
Order_Value            0
Discount_Applied       0
Final_Amount           0
Payment_Mode           0
Order_Status           0
Cancellation_Reason    0
Delivery_Partner_ID    0
Delivery_Rating        0
Restaurant_Rating      0
Order_Day              0
Peak_Hour              0
Profit_Margin          0
dtype: int64

In [ ]:
df.head()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,Hyderabad,Central,RES936,Restaurant_29,Chinese,2024-10-20,...,1156.0,UPI,Delivered,Not Cancelled,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,39.0,Female,Chennai,North,RES689,Restaurant_419,Chinese,2024-08-12,...,4849.0,COD,Delivered,Not Cancelled,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,39.0,Male,Delhi,South,RES723,Restaurant_244,Arabian,2024-12-08,...,737.0,Wallet,Delivered,Not Cancelled,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,39.0,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,2024-10-08,...,1156.0,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,False,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2024-02-04,...,352.0,Card,Delivered,Not Cancelled,DP728,2.0,4.4,Weekend,False,0.12

In [ ]:
df.Delivery_Time_Min.value_counts().sum()

np.int64(100000)

In [ ]:
df.to_csv("/content/cleaned_food_delivery.csv", index=False)

In [ ]:
from google.colab import files
files.download("cleaned_food_delivery.csv")

In [ ]:
df

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,Hyderabad,Central,RES936,Restaurant_29,Chinese,2024-10-20,...,1156.0,UPI,Delivered,Not Cancelled,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,39.0,Female,Chennai,North,RES689,Restaurant_419,Chinese,2024-08-12,...,4849.0,COD,Delivered,Not Cancelled,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,39.0,Male,Delhi,South,RES723,Restaurant_244,Arabian,2024-12-08,...,737.0,Wallet,Delivered,Not Cancelled,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,39.0,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,2024-10-08,...,1156.0,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,False,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2024-02-04,...,352.0,Card,Delivered,Not Cancelled,DP728,2.0,4.4,Weekend,False,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD099996,CUST3722,39.0,Other,Mumbai,South,RES295,Restaurant_500,Arabian,2024-06-10,...,132.0,Card,Delivered,Not Cancelled,DP835,2.0,4.0,Weekday,True,0.17
99996,ORD099997,CUST6158,39.0,Male,Mumbai,East,RES157,Restaurant_458,Arabian,2024-04-22,...,1078.0,Card,Delivered,Not Cancelled,DP476,4.0,3.5,Weekday,False,-0.15
99997,ORD099998,CUST2155,39.0,Other,Delhi,East,RES287,Restaurant_273,Indian,2024-02-23,...,1156.0,COD,Cancelled,Not Cancelled,DP577,2.0,4.0,Weekday,True,0.47
99998,ORD099999,CUST3015,39.0,Female,Delhi,North,RES491,Restaurant_241,Indian,2024-12-10,...,1156.0,Card,Delivered,Not Cancelled,DP896,3.0,4.3,Weekday,False,0.44
99999,ORD100000,CUST7959,39.0,Other,Hyderabad,East,RES680,Restaurant_237,Chinese,2024-07-15,...,1156.0,Wallet,Cancelled,Not Cancelled,DP908,5.0,4.2,Weekday,False,0.20

In [ ]:
df = pd.read_csv("/content/cleaned_food_delivery.csv")

In [ ]:
df.isnull().sum()

Order_ID               0
Customer_ID            0
Customer_Age           0
Customer_Gender        0
City                   0
Area                   0
Restaurant_ID          0
Restaurant_Name        0
Cuisine_Type           0
Order_Date             0
Order_Time             0
Delivery_Time_Min      0
Distance_km            0
Order_Value            0
Discount_Applied       0
Final_Amount           0
Payment_Mode           0
Order_Status           0
Cancellation_Reason    0
Delivery_Partner_ID    0
Delivery_Rating        0
Restaurant_Rating      0
Order_Day              0
Peak_Hour              0
Profit_Margin          0
dtype: int64

In [ ]:
df

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,Hyderabad,Central,RES936,Restaurant_29,Chinese,2024-10-20,...,1156.0,UPI,Delivered,Not Cancelled,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,39.0,Female,Chennai,North,RES689,Restaurant_419,Chinese,2024-08-12,...,4849.0,COD,Delivered,Not Cancelled,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,39.0,Male,Delhi,South,RES723,Restaurant_244,Arabian,2024-12-08,...,737.0,Wallet,Delivered,Not Cancelled,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,39.0,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,2024-10-08,...,1156.0,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,False,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2024-02-04,...,352.0,Card,Delivered,Not Cancelled,DP728,2.0,4.4,Weekend,False,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD099996,CUST3722,39.0,Other,Mumbai,South,RES295,Restaurant_500,Arabian,2024-06-10,...,132.0,Card,Delivered,Not Cancelled,DP835,2.0,4.0,Weekday,True,0.17
99996,ORD099997,CUST6158,39.0,Male,Mumbai,East,RES157,Restaurant_458,Arabian,2024-04-22,...,1078.0,Card,Delivered,Not Cancelled,DP476,4.0,3.5,Weekday,False,-0.15
99997,ORD099998,CUST2155,39.0,Other,Delhi,East,RES287,Restaurant_273,Indian,2024-02-23,...,1156.0,COD,Cancelled,Not Cancelled,DP577,2.0,4.0,Weekday,True,0.47
99998,ORD099999,CUST3015,39.0,Female,Delhi,North,RES491,Restaurant_241,Indian,2024-12-10,...,1156.0,Card,Delivered,Not Cancelled,DP896,3.0,4.3,Weekday,False,0.44
99999,ORD100000,CUST7959,39.0,Other,Hyderabad,East,RES680,Restaurant_237,Chinese,2024-07-15,...,1156.0,Wallet,Cancelled,Not Cancelled,DP908,5.0,4.2,Weekday,False,0.20

In [ ]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Age', 'Customer_Gender', 'City',
       'Area', 'Restaurant_ID', 'Restaurant_Name', 'Cuisine_Type',
       'Order_Date', 'Order_Time', 'Delivery_Time_Min', 'Distance_km',
       'Order_Value', 'Discount_Applied', 'Final_Amount', 'Payment_Mode',
       'Order_Status', 'Cancellation_Reason', 'Delivery_Partner_ID',
       'Delivery_Rating', 'Restaurant_Rating', 'Order_Day', 'Peak_Hour',
       'Profit_Margin'],
      dtype='object')

In [ ]:
df.groupby('Order_Status')[[
    'Delivery_Time_Min',
    'Distance_km',
    'Profit_Margin'
]].mean()

              Delivery_Time_Min  Distance_km  Profit_Margin
Order_Status
Cancelled            125.010442    14.252608       0.152379
Delivered            124.977002    14.285601       0.150005

In [ ]:
#✅ INSIGHT

Cancelled orders have higher delivery time and distance, and lower profit margin compared to completed orders.

In [ ]:
df.groupby(['Order_Status','City']).size()

Order_Status  City
Cancelled     Bangalore     2501
              Chennai       2482
              Delhi         2514
              Hyderabad     5078
              Mumbai        2461
Delivered     Bangalore    14231
              Chennai      13988
              Delhi        14181
              Hyderabad    28532
              Mumbai       14032
dtype: int64

In [ ]:
#INSIGHT---->Certain cities have higher cancellation counts, indicating city-level delivery issues.

In [ ]:
df.groupby(['Cuisine_Type','Order_Status']).size()

Cuisine_Type  Order_Status
Arabian       Cancelled        2458
              Delivered       14200
Chinese       Cancelled        2478
              Delivered       14173
Indian        Cancelled        5097
              Delivered       28473
Italian       Cancelled        2491
              Delivered       14028
Mexican       Cancelled        2512
              Delivered       14090
dtype: int64

In [ ]:
#INSIGHT--->Some cuisines experience higher cancellations, possibly due to preparation or delivery delays.

In [ ]:
df.groupby(['Order_Day','Order_Status']).size()

Order_Day  Order_Status
Weekday    Cancelled       10737
           Delivered       60633
Weekend    Cancelled        4299
           Delivered       24331
dtype: int64

In [ ]:
#INSIGHT--->Weekday show higher order volume and also higher cancellations.

In [ ]:
df[df['Order_Status']=='Cancelled']['Cancellation_Reason'].value_counts()

Cancellation_Reason
Not Cancelled         6005
Late Delivery         3059
Customer Cancelled    2993
Restaurant Issue      2979
Name: count, dtype: int64